### ISSUE TITLE
HTML generation

### ISSUE THREAD

**Issue by ymherklotz** [ymherklotz/FMark#36]
Generate HTML from the markdown parser, so that we can visualise the markdown in a browser. This will make FMark at least useable.

**Comment by ThunderMikey** [comment]
I am stuck with `strToc` function. All my work is in `htmlgenimpl` branch.

Since I have already been working on this for three days, and it's not working out, it's probably good to hand this to someone else while I move to bug fixes in the parser.

All you need to do is to convert `Ttoc` to `string` of HTML list. This function should be independent from the rest functions in `HTMLGen.fs`. You can use `attachSimpleTag` function to attach HTML tag to a string.

**Comment by ps-george** [comment]
@ThunderMikey was it just Ttoc -> string that needed doing?

**Comment by ThunderMikey** [comment]
We'll need to

* HTML `head` generation for including page meta data and CSS
* find a good CSS framework to style stuff, I reckon Bootstrap to start with 
* read markdown filename and put it into HTML title
* maybe more

**Comment by ThunderMikey** [comment]
#104 adds a top level function `genHTML` which will generate a fully working HTML document.
