### ISSUE TITLE
Command line Interface

### ISSUE THREAD

**Issue by ymherklotz** [ymherklotz/FMark#38]
Add a CLI so that the GUI can call it with the specific flags. This will be the main way to interact with FMark, whatever the GUI framework is.

**Comment by ymherklotz** [comment]
The options to implement are:
- `-l` / `--loglevel`: set the loglevel ('DEBUG', 'INFO', 'WARNING', 'ERROR').
- `-o` / `--output`: name the output file.
- `--format`: name the output format, by default: `html`.

**Comment by ymherklotz** [comment]
@ps-george `--input` can just be the last argument right? just like `gcc -o out in` -> `fmark -o out in`. But if you prefer we can keep `--input`

**Comment by ps-george** [comment]
Think I've got it so all the following are valid `fmark -i in -o out` or  `fmark -o out in` or `result > fmark -o out -s` (-s for stdin, )

**Comment by ps-george** [comment]
Not sure how to set the log level from CLI, since you'd have to initialise the logger in the earliest included file (so that the logger level is set globally across all parts), but then you only know what the level will be when the top level function is called.

If the logger had a change state function, we could initialise the logger in Shared.fs (or even in Logger.fs to reduce dependency), and then called logger.changeState(LogLevel) from FMarkCLI.fs

**Comment by ymherklotz** [comment]
Yeah I had already implemented that but took it away, you just have to make it mutable

**Comment by ymherklotz** [comment]
I can implement the command line option if you want thoigh

**Comment by ps-george** [comment]
Yeah it's really messy at the moment to initialise the logger in every file you use it, and then all the different loggers have different levels that they print out for.

Not very functional but I think we need it to be mutable, and sure 👍

**Comment by ps-george** [comment]
Implemented mutable globLog, can change log level from command line :D
